In [1]:
# This is the first guided capstone project
#The project is to make a recommendation to Big Mountain Resort to add additional liftchair to help distribution the visitors
# This part contains the Data Wrangling, which include the data collection, Data Organize,Data Defination and Data Clean
#The idea to improve the distribution of guest is calculate the area vs. liftchair and compare with average in the nation. s
# Part 1, Data Collection. The data file is called resort.csv and saveed in the local C drive. So use Python to read the data

#Import functions for the project
import pandas as pd
import numpy as np

#Load the pyplot collection of functions from matplotlib, as plt. This will be for the data visualization part 
import matplotlib.pyplot as plt

In [2]:
# Data collection- Import data file resort.csv to a new DaraFrame resort_orignal and compared with original excel spreadsheet
resort_original = pd.read_csv(r"C:\\Users\\mohua\\OneDrive\\Documents\\unit6\resort.csv", index_col=None)
resort_original.shape
resort_original.head()
# The data has 330 column, 27 rows, which did not lose the data. So resort_original will be the raw data for the processing

,Name,Region,state,summit_elev,vertical_drop,base_elev,trams,fastEight,fastSixes,fastQuads,...,LongestRun_mi,SkiableTerrain_ac,Snow Making_ac,daysOpenLastYear,yearsOpen,averageSnowfall,AdultWeekday,AdultWeekend,projectedDaysOpen,NightSkiing_ac
0,Alyeska Resort,Alaska,Alaska,3939,2500,250,1,0.0,0,2,...,1.0,1610.0,113.0,150.0,60.0,669.0,65.0,85.0,150.0,550.0
1,Eaglecrest Ski Area,Alaska,Alaska,2600,1540,1200,0,0.0,0,0,...,2.0,640.0,60.0,45.0,44.0,350.0,47.0,53.0,90.0,NaN
2,Hilltop Ski Area,Alaska,Alaska,2090,294,1796,0,0.0,0,0,...,1.0,30.0,30.0,150.0,36.0,69.0,30.0,34.0,152.0,30.0
3,Arizona Snowbowl,Arizona,Arizona,11500,2300,9200,0,0.0,1,0,...,2.0,777.0,104.0,122.0,81.0,260.0,89.0,89.0,122.0,NaN
4,Sunrise Park Resort,Arizona,Arizona,11100,1800,9200,0,NaN,0,1,...,1.2,800.0,80.0,115.0,49.0,250.0,74.0,78.0,104.0,80.0

In [3]:
# Part 2, Data organize and clean
# first check the duplicate, we found that "Region" seems to be redudant data. The 'tranms' also does not help for this project
# So drop these two columns
resort=resort_original.drop(['Region','trams'], axis=1)
# There is also another spelling confustion. Per information, the "Surface" represents 'single' liftchair. To make it clear, change the column index to 'single'
resort.rename(columns={'surface': 'single'}, inplace=True)
resort.head()
#Checked and looks good

# We initially want to compare the situation in Montana, but found there are only two data. So the idea is abandoned.Use the whole data
#resort_montana=resort[resort['state']=='Montana']
#resort=resort_montana
# There are some numbers,such as 0,1,2,... from csv file. To better process data, we need to eliminate that column
# The idea to eliminate that column is to switch columns and rows. Then set 0,1,2... row as index. Use row 1 to substitue index and delete one role
# Switch columns and rows and reset index
resort_T=resort.T
resort_T.index
resort_T.reset_index()
#Use the first columns to subsittue index and then drop index row
resort_T.columns = resort_T.iloc[0]
resort_T=resort_T.drop(resort_T.index[0])
#Checked and looked good and then switch back to resort
resort=resort_T.T
resort.shape

(330, 24)

In [4]:
# The data has been checked again to ensure that there is no missing data 
resort.count()
# Apparantly, there are missing data, such as fastEight,TerrainParks, LogestRun_mi,etc..

state                330
summit_elev          330
vertical_drop        330
base_elev            330
fastEight            164
fastSixes            330
fastQuads            330
quad                 330
triple               330
double               330
single               330
total_chairs         330
Runs                 326
TerrainParks         279
LongestRun_mi        325
SkiableTerrain_ac    327
Snow Making_ac       284
daysOpenLastYear     279
yearsOpen            329
averageSnowfall      316
AdultWeekday         276
AdultWeekend         279
projectedDaysOpen    283
NightSkiing_ac       187
dtype: int64

In [5]:
# Use a simple command to drop the results with missing value and reset to the resort_clean
resort_clean=resort.dropna()
resort_clean.shape
resort_clean.count()
#Looks good. There are 41 data for the future analysis (24 columns and 41 rows)

state                41
summit_elev          41
vertical_drop        41
base_elev            41
fastEight            41
fastSixes            41
fastQuads            41
quad                 41
triple               41
double               41
single               41
total_chairs         41
Runs                 41
TerrainParks         41
LongestRun_mi        41
SkiableTerrain_ac    41
Snow Making_ac       41
daysOpenLastYear     41
yearsOpen            41
averageSnowfall      41
AdultWeekday         41
AdultWeekend         41
projectedDaysOpen    41
NightSkiing_ac       41
dtype: int64

In [6]:
#check column name
resort_clean.head()
resort_clean.shape
#(column 41, rows 24)
resort_clean.dtypes
# all data type are object,try to change some to the int
cols_int= ['fastEight','fastSixes', 'fastQuads', 'quad', 'triple',
        'double', 'single', 'total_chairs','Runs','TerrainParks','daysOpenLastYear','yearsOpen','AdultWeekday',
        'AdultWeekend','projectedDaysOpen']
resort_clean[cols_int] = resort_clean[cols_int].astype(int)
# all data type are object,try to change some to the float
cols_float = ['summit_elev', 'vertical_drop', 'base_elev','LongestRun_mi','SkiableTerrain_ac','Snow Making_ac',
              'averageSnowfall','NightSkiing_ac']
resort_clean[cols_float] = resort_clean[cols_float].astype(float)
# state should be string
cols_str=['state']
resort_clean[cols_str]=resort_clean[cols_str].astype(str)

#resort_clean['summit_elev']=resort_clean.summit_elev.astype('int64')

resort_clean.dtypes

C:\Users\mohua\anaconda3\lib\site-packages\pandas\core\frame.py:2963: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state                 object
summit_elev          float64
vertical_drop        float64
base_elev            float64
fastEight              int32
fastSixes              int32
fastQuads              int32
quad                   int32
triple                 int32
double                 int32
single                 int32
total_chairs           int32
Runs                   int32
TerrainParks           int32
LongestRun_mi        float64
SkiableTerrain_ac    float64
Snow Making_ac       float64
daysOpenLastYear       int32
yearsOpen              int32
averageSnowfall      float64
AdultWeekday           int32
AdultWeekend           int32
projectedDaysOpen      int32
NightSkiing_ac       float64
dtype: object

In [7]:
#output the data file to review
resort_clean.to_csv(r"C:\\Users\\mohua\\OneDrive\\Documents\\unit6\resort_clean.csv")